-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 22:40:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escola_Musica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escola_Musica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola_Musica` DEFAULT CHARACTER SET utf8 ;
USE `Escola_Musica` ;

-- -----------------------------------------------------
-- Table `Escola_Musica`.`Dim_Orquestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Dim_Orquestra` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Dim_Orquestra` (
  `idDim_Orquestra` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Data_criacao` DATETIME NOT NULL,
  PRIMARY KEY (`idDim_Orquestra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica`.`Dim_Sinfonia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Dim_Sinfonia` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Dim_Sinfonia` (
  `idDim_Sinfonia` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Compositor` VARCHAR(45) NOT NULL,
  `Data_Criacao` DATETIME NOT NULL,
  PRIMARY KEY (`idDim_Sinfonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica`.`Dim_Musico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Dim_Musico` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Dim_Musico` (
  `idDim_Musico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Nacionalidade` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATETIME NOT NULL,
  `Dim_Orquestra_idDim_Orquestra` INT NOT NULL,
  PRIMARY KEY (`idDim_Musico`, `Dim_Orquestra_idDim_Orquestra`),
  INDEX `fk_Dim_Musico_Dim_Orquestra1_idx` (`Dim_Orquestra_idDim_Orquestra` ASC) VISIBLE,
  CONSTRAINT `fk_Dim_Musico_Dim_Orquestra1`
    FOREIGN KEY (`Dim_Orquestra_idDim_Orquestra`)
    REFERENCES `Escola_Musica`.`Dim_Orquestra` (`idDim_Orquestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica`.`Dim_Instrumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Dim_Instrumento` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Dim_Instrumento` (
  `Id_Instrumento` INT NOT NULL,
  `Nome_Instrumento` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Instrumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica`.`Dim_Funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Dim_Funcao` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Dim_Funcao` (
  `ID_Funcao` INT NOT NULL,
  `Nome_Funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Funcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Musica`.`Fato_Apresentacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escola_Musica`.`Fato_Apresentacao` ;

CREATE TABLE IF NOT EXISTS `Escola_Musica`.`Fato_Apresentacao` (
  `Dim_Orquestra_idDim_Orquestra` INT NOT NULL,
  `Dim_Sinfonia_idDim_Sinfonia` INT NOT NULL,
  `Dim_Musico_idDim_Musico` INT NOT NULL,
  `Dim_Instrumento_Id_Instrumento` INT NOT NULL,
  `Dim_Funcao_ID_Funcao` INT NOT NULL,
  INDEX `fk_Fato_Apresentacao_Dim_Orquestra_idx` (`Dim_Orquestra_idDim_Orquestra` ASC) VISIBLE,
  INDEX `fk_Fato_Apresentacao_Dim_Sinfonia1_idx` (`Dim_Sinfonia_idDim_Sinfonia` ASC) VISIBLE,
  INDEX `fk_Fato_Apresentacao_Dim_Musico1_idx` (`Dim_Musico_idDim_Musico` ASC) VISIBLE,
  INDEX `fk_Fato_Apresentacao_Dim_Instrumento1_idx` (`Dim_Instrumento_Id_Instrumento` ASC) VISIBLE,
  INDEX `fk_Fato_Apresentacao_Dim_Funcao1_idx` (`Dim_Funcao_ID_Funcao` ASC) VISIBLE,
  CONSTRAINT `fk_Fato_Apresentacao_Dim_Orquestra`
    FOREIGN KEY (`Dim_Orquestra_idDim_Orquestra`)
    REFERENCES `Escola_Musica`.`Dim_Orquestra` (`idDim_Orquestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Apresentacao_Dim_Sinfonia1`
    FOREIGN KEY (`Dim_Sinfonia_idDim_Sinfonia`)
    REFERENCES `Escola_Musica`.`Dim_Sinfonia` (`idDim_Sinfonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Apresentacao_Dim_Musico1`
    FOREIGN KEY (`Dim_Musico_idDim_Musico`)
    REFERENCES `Escola_Musica`.`Dim_Musico` (`idDim_Musico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Apresentacao_Dim_Instrumento1`
    FOREIGN KEY (`Dim_Instrumento_Id_Instrumento`)
    REFERENCES `Escola_Musica`.`Dim_Instrumento` (`Id_Instrumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Apresentacao_Dim_Funcao1`
    FOREIGN KEY (`Dim_Funcao_ID_Funcao`)
    REFERENCES `Escola_Musica`.`Dim_Funcao` (`ID_Funcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
